name: Build
on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - name: Install dependencies
              run: yarn install
            - name: Check eslint
              run: yarn lint
            - name: Test app
              run: yarn test:ci
            # - name: SonarCloud Scan
            #  uses: SonarSource/sonarcloud-github-action@master
            #  env:
            #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} Needed to get PR information, if any
            #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            - name: Build app
              run: yarn build
